# who @#$%ing knows
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# mod attributes
mod_id=zconaddon
mod_name=Zirconium
mod_description=nah id win
maven_group=com.odtheking
archives_base_name=zirconium

# double check every so often
loader_version=0.19.3
loom_version=1.16-SNAPSHOT
fabric_kotlin_version=1.13.12+kotlin.2.4.0
fabric_api_version=0.151.0+26.1.2
devauth_version=1.2.1
commodore_version=1.0.1
kotlin_version=2.4.0
kotlin.code.style=official
minecraft_lwjgl_version=3.4.1

# the important stuff
minecraft_version=26.1.2
odin_version=0.3.2
mod_version=0.0.28